import {
    ActivitySquare,
    BadgeCheck,
    BedDouble,
    CalendarClock,
    CalendarDays,
    CalendarRange,
    CalendarSync,
    ChartNoAxesCombined,
    ClipboardCheck,
    ClipboardList,
    ClockAlert,
    DownloadCloud,
    FilePlus2,
    FileText,
    Fingerprint,
    History,
    ListChecks,
    ListFilter,
    ListTodo,
    MapPinned,
    MonitorCog,
    Pill,
    Route,
    SearchCheck,
    Send,
    Smartphone,
    SmartphoneNfc,
    UserRoundCog,
    Wifi,
} from '@lucide/vue';
import type { Component } from 'vue';

const icons: Record<string, Component> = {
    ActivitySquare,
    BadgeCheck,
    BedDouble,
    CalendarClock,
    CalendarDays,
    CalendarRange,
    CalendarSync,
    ChartNoAxesCombined,
    ClipboardCheck,
    ClipboardList,
    ClockAlert,
    DownloadCloud,
    FilePlus2,
    FileText,
    Fingerprint,
    History,
    ListChecks,
    ListFilter,
    ListTodo,
    MapPinned,
    MonitorCog,
    Pill,
    Route,
    SearchCheck,
    Send,
    Smartphone,
    SmartphoneNfc,
    UserRoundCog,
    Wifi,
};

export function ambilIconBpjs(name: string): Component {
    return icons[name] ?? FileText;
}
